jisuhsyuf

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -15,6 +15,13 @@ env:
   IP_LIST: "20.156.185.44,20.156.185.45,20.156.185.43,20.156.185.15,10.222.201.9" 
 
 jobs:
+  # check-connectivity:
+  #   runs-on: self-hosted
+
+  #   steps: 
+  #     - name: Check out repository
+  #       uses: actions/checkout@v3
+      
   check-image:
     runs-on: self-hosted
     
@@ -22,84 +29,65 @@ jobs:
       - name: check docker image
         run: docker images
 
-  load-image:
-    needs: check-image
-    runs-on: self-hosted
-    steps:
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: my-docker-image
-          path: /tmp
-
-      - name: Load image
-        run: |
-          docker load --input /tmp/my-docker-image.tar
-          docker image ls -a
-  
-  # check-connectivity:
-  #   runs-on: self-hosted
-
-  #   steps: 
-  #     - name: Check out repository
-  #       uses: actions/checkout@v3
-
-  #     # - name: run docker container
-  #     #   run: docker run --name my-docker-container -d my-docker-image "tail -f /dev/null"
-      
-  # check-image:
-  #   runs-on: self-hosted
-    
-  #   steps:
-  #     - name: check docker image
-  #       run: docker images
-
   check-connectivity:
     needs: load-image
     runs-on: self-hosted
-    container:
-      image: my-docker-image
+    # container:
+    #   image: my-docker-image
 
     steps:
       - name: Check out repository
         uses: actions/checkout@v3
 
-      - name: Install Netcat
-        run: |
-          if [ -x "$(command -v apk)" ]; then
-            apk add --no-cache netcat-openbsd
-          elif [ -x "$(command -v apt-get)" ]; then
-            sudo apt-get update && sudo apt-get install -y netcat
-          elif [ -x "$(command -v yum)" ]; then
-            sudo yum install -y nc
-          else
-            echo "Package manager not supported. Unable to install netcat."
-           exit 1
-          fi
+      # - name: Install Netcat
+      #   run: |
+      #     if [ -x "$(command -v apk)" ]; then
+      #       apk add --no-cache netcat-openbsd
+      #     elif [ -x "$(command -v apt-get)" ]; then
+      #       sudo apt-get update && sudo apt-get install -y netcat
+      #     elif [ -x "$(command -v yum)" ]; then
+      #       sudo yum install -y nc
+      #     else
+      #       echo "Package manager not supported. Unable to install netcat."
+      #      exit 1
+      #     fi
           
       - name: Check Network Connectivity
-        run: |
+        with:
+          image: my-docker-image
+            run: |
           
-          # Initialize a variable to track failures
-          ALL_SUCCESS=true
-          # Split the IP_LIST into an array using IFS
-          IFS=','; for IP in $IP_LIST; do
-            echo "Checking connectivity to $IP on port 22..."
-            # Use netcat to check connectivity on port 22 (SSH)
-            if nc -z -w 5 "$IP" 22 &>/dev/null; then
-              echo "✅ Connectivity to $IP on port 22 exists."
-            else
-              echo "❌ Cannot connect to $IP on port 22. Please check network/firewall settings."
-              ALL_SUCCESS=false
-            fi
-          done
-          # Display final result
-          if [ "$ALL_SUCCESS" = true ]; then
-            echo "✅ All IPs are reachable on port 22."
-          else
-            echo "❌ Some IPs are not reachable on port 22. Please check the connectivity."
-            exit 1
-          fi
+              if [ -x "$(command -v apk)" ]; then
+                apk add --no-cache netcat-openbsd
+              elif [ -x "$(command -v apt-get)" ]; then
+                sudo apt-get update && sudo apt-get install -y netcat
+              elif [ -x "$(command -v yum)" ]; then
+                sudo yum install -y nc
+              else
+                echo "Package manager not supported. Unable to install netcat."
+              exit 1
+              fi
+
+              # Initialize a variable to track failures
+              ALL_SUCCESS=true
+              # Split the IP_LIST into an array using IFS
+              IFS=','; for IP in $IP_LIST; do
+                echo "Checking connectivity to $IP on port 22..."
+                # Use netcat to check connectivity on port 22 (SSH)
+                if nc -z -w 5 "$IP" 22 &>/dev/null; then
+                  echo "✅ Connectivity to $IP on port 22 exists."
+                else
+                  echo "❌ Cannot connect to $IP on port 22. Please check network/firewall settings."
+                  ALL_SUCCESS=false
+                fi
+              done
+              # Display final result
+              if [ "$ALL_SUCCESS" = true ]; then
+                echo "✅ All IPs are reachable on port 22."
+              else
+                echo "❌ Some IPs are not reachable on port 22. Please check the connectivity."
+                exit 1
+              fi
  
 
       # - name: Running container
