xgds

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,10 +1,12 @@
 name: CD
 
 on:
-  push:
-    branches: [main]
-    # paths:
-    #   - '.github/workflows/sample-ping.yml'
+  # push:
+  #   branches: [main]
+  workflow_run:
+    workflows: ["CI"]
+    types:
+      - completed
 
 env:
   ENABLE_DOWNLOADS_FROM_ARTIFACTORY: false # Optional variable to enable Artifactory downloads
@@ -23,33 +25,89 @@ jobs:
       # - name: run docker container
       #   run: docker run --name my-docker-container -d my-docker-image "tail -f /dev/null"
       
-          
-      - name: Running container
+  check-image:
+    runs-on: self-hosted
+    
+    steps:
+      - name: check docker image
+        run: docker images
+
+  check-connectivity:
+    runs-on: self-hosted
+    container:
+      image: artifactory-alpine:latest
+
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Install Netcat
         run: |
-          echo "Starting Docker container..."
-          docker run --rm -v "$(pwd)":/workspace -w /workspace -e IP_LIST my-docker-image:latest sh -c '
-            if command -v apk > /dev/null 2>&1; then
-              apk add --no-cache netcat-openbsd
-            elif command -v apt-get > /dev/null 2>&1; then
-              apt-get update && apt-get install -y netcat
-            elif command -v yum > /dev/null 2>&1; then
-              yum install -y nc
-            else
-              echo "Package manager not supported. Unable to install netcat."
-            fi
+          if [ -x "$(command -v apk)" ]; then
+            apk add --no-cache netcat-openbsd
+          elif [ -x "$(command -v apt-get)" ]; then
+            sudo apt-get update && sudo apt-get install -y netcat
+          elif [ -x "$(command -v yum)" ]; then
+            sudo yum install -y nc
+          else
+            echo "Package manager not supported. Unable to install netcat."
+           exit 1
+          fi
           
-            # Initialize a variable to track failures
-            ALL_SUCCESS=true
-            echo "list all the ip s - ${IP_LIST}"
-            # Split the IP_LIST into an array using IFS
-            IFS=","; for IP in $IP_LIST; do
-              echo "Checking connectivity to $IP on port 22..."
-              # Use netcat to check connectivity on port 22 (SSH)
-              if nc -z -w 5 "$IP" 22 >/dev/null 2>&1; then
-                echo "✅ Connectivity to $IP on port 22 exists."
-              else
-                echo "❌ Cannot connect to $IP on port 22. Please check network/firewall settings."
-                ALL_SUCCESS=false
-              fi
-              done
-              echo "end of file"'
+      - name: Check Network Connectivity
+        run: |
+          
+          # Initialize a variable to track failures
+          ALL_SUCCESS=true
+          # Split the IP_LIST into an array using IFS
+          IFS=','; for IP in $IP_LIST; do
+            echo "Checking connectivity to $IP on port 22..."
+            # Use netcat to check connectivity on port 22 (SSH)
+            if nc -z -w 5 "$IP" 22 &>/dev/null; then
+              echo "✅ Connectivity to $IP on port 22 exists."
+            else
+              echo "❌ Cannot connect to $IP on port 22. Please check network/firewall settings."
+              ALL_SUCCESS=false
+            fi
+          done
+          # Display final result
+          if [ "$ALL_SUCCESS" = true ]; then
+            echo "✅ All IPs are reachable on port 22."
+          else
+            echo "❌ Some IPs are not reachable on port 22. Please check the connectivity."
+            exit 1
+          fi
+
+
+
+ 
+      # - name: Running container
+      #   run: |
+      #     echo "Starting Docker container..."
+      #     export IP_LIST="${IP_LIST}"
+      #     docker run --rm -v "$(pwd)":/workspace -w /workspace -e IP_LIST my-docker-image:latest sh -c '
+      #       if command -v apk > /dev/null 2>&1; then
+      #         apk add --no-cache netcat-openbsd
+      #       elif command -v apt-get > /dev/null 2>&1; then
+      #         apt-get update && apt-get install -y netcat
+      #       elif command -v yum > /dev/null 2>&1; then
+      #         yum install -y nc
+      #       else
+      #         echo "Package manager not supported. Unable to install netcat."
+      #       fi
+          
+      #       # Initialize a variable to track failures
+      #       ALL_SUCCESS=true
+      #       echo "list all the ip s - ${IP_LIST}"
+      #       # Split the IP_LIST into an array using IFS
+      #       IFS=","; for IP in $IP_LIST; do
+      #         echo "Checking connectivity to $IP on port 22..."
+      #         # Use netcat to check connectivity on port 22 (SSH)
+      #         if nc -z -w 5 "$IP" 22 >/dev/null 2>&1; then
+      #           echo "✅ Connectivity to $IP on port 22 exists."
+      #         else
+      #           echo "❌ Cannot connect to $IP on port 22. Please check network/firewall settings."
+      #           ALL_SUCCESS=false
+      #         fi
+      #         done
+      #         echo "end of file"'
