ffduckdfd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -24,22 +24,8 @@ jobs:
       #   run: docker run --name my-docker-container -d my-docker-image "tail -f /dev/null"
       
           
-      # - name: Install Netcat
-      #   run: |
-      #     if [ -x "$(command -v apk)" ]; then
-      #       apk add --no-cache netcat-openbsd
-      #     elif [ -x "$(command -v apt-get)" ]; then
-      #       sudo apt-get update && sudo apt-get install -y netcat
-      #     elif [ -x "$(command -v yum)" ]; then
-      #       sudo yum install -y nc
-      #     else
-      #       echo "Package manager not supported. Unable to install netcat."
-      #      exit 1
-      #     fi
       - name: Install Netcat
         run: |
-          echo "Starting Docker container..."
-          docker run --rm -v "$(pwd)":/workspace -w /workspace my-docker-image:latest bash -c "
           if [ -x "$(command -v apk)" ]; then
             apk add --no-cache netcat-openbsd
           elif [ -x "$(command -v apt-get)" ]; then
@@ -48,8 +34,22 @@ jobs:
             sudo yum install -y nc
           else
             echo "Package manager not supported. Unable to install netcat."
-          exit 1
-          fi"
+           exit 1
+          fi
+      - name: Install Netcat
+        run: |
+          echo "Starting Docker container..."
+          docker run --rm -v "$(pwd)":/workspace -w /workspace my-docker-image:latest bash -c "
+            if [ -x "$(command -v apk)" ]; then
+              apk add --no-cache netcat-openbsd
+            elif [ -x "$(command -v apt-get)" ]; then
+              sudo apt-get update && sudo apt-get install -y netcat
+            elif [ -x "$(command -v yum)" ]; then
+              sudo yum install -y nc
+            else
+              echo "Package manager not supported. Unable to install netcat."
+            exit 1
+            fi"
 
       # - name: Ping IP's
       #   run: |
