ab sahi kia

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -13,7 +13,6 @@ env:
 
 jobs:
   check-connectivity:
-    needs: download-artifact
     runs-on: self-hosted
 
     steps: 
@@ -26,16 +25,19 @@ jobs:
           
       - name: Install Netcat
         run: |
-          if [ -x "$(command -v apk)" ]; then
-            apk add --no-cache netcat-openbsd
-          elif [ -x "$(command -v apt-get)" ]; then
-            sudo apt-get update && sudo apt-get install -y netcat
-          elif [ -x "$(command -v yum)" ]; then
-            sudo yum install -y nc
-          else
-            echo "Package manager not supported. Unable to install netcat."
-           exit 1
-          fi
+          echo "Starting Docker container..."
+          docker run --rm -v "$(pwd)":/workspace -w /workspace my-docker-image:latest bash -c "
+            if [ -x "$(command -v apk)" ]; then
+              apk add --no-cache netcat-openbsd
+            elif [ -x "$(command -v apt-get)" ]; then
+              sudo apt-get update && sudo apt-get install -y netcat
+            elif [ -x "$(command -v yum)" ]; then
+              sudo yum install -y nc
+            else
+              echo "Package manager not supported. Unable to install netcat."
+            exit 1
+            fi
+          "
 
       # - name: Ping IP's
       #   run: |
