update-code

diff --git a/.github/workflows/sample-ping.yml b/.github/workflows/sample-ping.yml
--- a/.github/workflows/sample-ping.yml
+++ b/.github/workflows/sample-ping.yml
@@ -34,18 +34,18 @@ jobs:
           sudo ufw status
           # sudo ufw show added
           
-      - name: Install Netcat
-        run: |
-          if [ -x "$(command -v apk)" ]; then
-            apk add --no-cache netcat-openbsd
-          elif [ -x "$(command -v apt-get)" ]; then
-            sudo apt-get update && sudo apt-get install -y netcat
-          elif [ -x "$(command -v yum)" ]; then
-            sudo yum install -y nc
-          else
-            echo "Package manager not supported. Unable to install netcat."
-           exit 1
-          fi
+      # - name: Install Netcat
+      #   run: |
+      #     if [ -x "$(command -v apk)" ]; then
+      #       apk add --no-cache netcat-openbsd
+      #     elif [ -x "$(command -v apt-get)" ]; then
+      #       sudo apt-get update && sudo apt-get install -y netcat
+      #     elif [ -x "$(command -v yum)" ]; then
+      #       sudo yum install -y nc
+      #     else
+      #       echo "Package manager not supported. Unable to install netcat."
+      #      exit 1
+      #     fi
           
       # - name: Ping IP's
       #   run: |
